apiVersion: skaffold/v4beta4
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  googleCloudBuild:
    projectId: ticketing-dev-385306
  artifacts:
    - image: us.gcr.io/ticketing-dev-385306/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
